// Comprehensive South African place list for location autocomplete.
//
// ~250 entries covering all 9 provinces, major cities, key suburbs, and
// popular lifestyle areas used in the SA property market. Searched locally
// (no network call, no API key, instant response).

class SaPlace {
  final String name;

  /// Short context shown as subtitle in the picker row.
  final String label;

  /// SA province this place belongs to (empty for province-level entries).
  final String province;

  /// True only for the 9 province entries themselves.
  final bool isProvince;

  const SaPlace(
    this.name,
    this.label, {
    this.province = '',
    this.isProvince = false,
  });
}

abstract final class SaPlaces {
  // --------------------------------------------------------------------------
  // Search
  // --------------------------------------------------------------------------

  /// Returns up to 8 places matching [query] (case-insensitive, substring).
  static List<SaPlace> search(String query) {
    if (query.trim().isEmpty) return [];
    final q = query.toLowerCase().trim();
    return all
        .where((p) =>
            p.name.toLowerCase().contains(q) ||
            p.label.toLowerCase().contains(q))
        .take(8)
        .toList();
  }

  // --------------------------------------------------------------------------
  // Complete place list
  // --------------------------------------------------------------------------

  static const List<SaPlace> all = [
    // ── PROVINCES ────────────────────────────────────────────────────────────
    SaPlace('Gauteng', 'Province', isProvince: true),
    SaPlace('Western Cape', 'Province', isProvince: true),
    SaPlace('KwaZulu-Natal', 'Province', isProvince: true),
    SaPlace('Eastern Cape', 'Province', isProvince: true),
    SaPlace('Free State', 'Province', isProvince: true),
    SaPlace('Limpopo', 'Province', isProvince: true),
    SaPlace('Mpumalanga', 'Province', isProvince: true),
    SaPlace('North West', 'Province', isProvince: true),
    SaPlace('Northern Cape', 'Province', isProvince: true),

    // ── GAUTENG ──────────────────────────────────────────────────────────────
    SaPlace('Johannesburg', 'Gauteng', province: 'Gauteng'),
    SaPlace('Sandton', 'Johannesburg', province: 'Gauteng'),
    SaPlace('Bryanston', 'Johannesburg', province: 'Gauteng'),
    SaPlace('Hyde Park', 'Johannesburg', province: 'Gauteng'),
    SaPlace('Rosebank', 'Johannesburg', province: 'Gauteng'),
    SaPlace('Parkhurst', 'Johannesburg', province: 'Gauteng'),
    SaPlace('Greenside', 'Johannesburg', province: 'Gauteng'),
    SaPlace('Linden', 'Johannesburg', province: 'Gauteng'),
    SaPlace('Northcliff', 'Johannesburg', province: 'Gauteng'),
    SaPlace('Houghton Estate', 'Johannesburg', province: 'Gauteng'),
    SaPlace('Morningside', 'Johannesburg', province: 'Gauteng'),
    SaPlace('Illovo', 'Johannesburg', province: 'Gauteng'),
    SaPlace('Melrose', 'Johannesburg', province: 'Gauteng'),
    SaPlace('Rivonia', 'Johannesburg', province: 'Gauteng'),
    SaPlace('Sunninghill', 'Johannesburg', province: 'Gauteng'),
    SaPlace('Woodmead', 'Johannesburg', province: 'Gauteng'),
    SaPlace('Lone Hill', 'Johannesburg', province: 'Gauteng'),
    SaPlace('Paulshof', 'Johannesburg', province: 'Gauteng'),
    SaPlace('Fourways', 'Johannesburg', province: 'Gauteng'),
    SaPlace('Douglasdale', 'Johannesburg', province: 'Gauteng'),
    SaPlace('Randpark Ridge', 'Johannesburg', province: 'Gauteng'),
    SaPlace('Northriding', 'Johannesburg', province: 'Gauteng'),
    SaPlace('Randburg', 'Johannesburg', province: 'Gauteng'),
    SaPlace('Norwood', 'Johannesburg', province: 'Gauteng'),
    SaPlace('Orange Grove', 'Johannesburg', province: 'Gauteng'),
    SaPlace('Kensington', 'Johannesburg', province: 'Gauteng'),
    SaPlace('Bedfordview', 'Johannesburg', province: 'Gauteng'),
    SaPlace('Edenvale', 'Johannesburg', province: 'Gauteng'),
    SaPlace('Roodepoort', 'Gauteng', province: 'Gauteng'),
    SaPlace('Weltevreden Park', 'Roodepoort', province: 'Gauteng'),
    SaPlace('Florida', 'Roodepoort', province: 'Gauteng'),
    SaPlace('Soweto', 'Johannesburg', province: 'Gauteng'),
    SaPlace('Diepsloot', 'Johannesburg', province: 'Gauteng'),
    SaPlace('Alexandra', 'Johannesburg', province: 'Gauteng'),
    SaPlace('Pretoria', 'Gauteng', province: 'Gauteng'),
    SaPlace('Hatfield', 'Pretoria', province: 'Gauteng'),
    SaPlace('Menlo Park', 'Pretoria', province: 'Gauteng'),
    SaPlace('Brooklyn', 'Pretoria', province: 'Gauteng'),
    SaPlace('Lynnwood', 'Pretoria', province: 'Gauteng'),
    SaPlace('Waterkloof', 'Pretoria', province: 'Gauteng'),
    SaPlace('Waterkloof Ridge', 'Pretoria', province: 'Gauteng'),
    SaPlace('Faerie Glen', 'Pretoria', province: 'Gauteng'),
    SaPlace('Garsfontein', 'Pretoria', province: 'Gauteng'),
    SaPlace('Silver Lakes', 'Pretoria', province: 'Gauteng'),
    SaPlace('Erasmuskloof', 'Pretoria', province: 'Gauteng'),
    SaPlace('Montana', 'Pretoria', province: 'Gauteng'),
    SaPlace('Sinoville', 'Pretoria', province: 'Gauteng'),
    SaPlace('Wonderboom', 'Pretoria', province: 'Gauteng'),
    SaPlace('Atteridgeville', 'Pretoria', province: 'Gauteng'),
    SaPlace('Pretoria East', 'Pretoria', province: 'Gauteng'),
    SaPlace('Pretoria North', 'Pretoria', province: 'Gauteng'),
    SaPlace('Centurion', 'Gauteng', province: 'Gauteng'),
    SaPlace('Irene', 'Centurion', province: 'Gauteng'),
    SaPlace('Die Hoewes', 'Centurion', province: 'Gauteng'),
    SaPlace('Eldoraigne', 'Centurion', province: 'Gauteng'),
    SaPlace('Wierdapark', 'Centurion', province: 'Gauteng'),
    SaPlace('Lyttelton', 'Centurion', province: 'Gauteng'),
    SaPlace('Midrand', 'Gauteng', province: 'Gauteng'),
    SaPlace('Kyalami', 'Midrand', province: 'Gauteng'),
    SaPlace('Waterfall', 'Midrand', province: 'Gauteng'),
    SaPlace('Dainfern', 'Midrand', province: 'Gauteng'),
    SaPlace('Steyn City', 'Midrand', province: 'Gauteng'),
    SaPlace('Halfway House', 'Midrand', province: 'Gauteng'),
    SaPlace('Kempton Park', 'Gauteng', province: 'Gauteng'),
    SaPlace('Benoni', 'Gauteng', province: 'Gauteng'),
    SaPlace('Boksburg', 'Gauteng', province: 'Gauteng'),
    SaPlace('Germiston', 'Gauteng', province: 'Gauteng'),
    SaPlace('Alberton', 'Gauteng', province: 'Gauteng'),
    SaPlace('Vereeniging', 'Gauteng', province: 'Gauteng'),
    SaPlace('Krugersdorp', 'Gauteng', province: 'Gauteng'),
    SaPlace('Brakpan', 'Gauteng', province: 'Gauteng'),
    SaPlace('Springs', 'Gauteng', province: 'Gauteng'),
    SaPlace('Tembisa', 'Gauteng', province: 'Gauteng'),
    SaPlace('Hartbeespoort', 'North West', province: 'North West'),

    // ── WESTERN CAPE ─────────────────────────────────────────────────────────
    SaPlace('Cape Town', 'Western Cape', province: 'Western Cape'),
    SaPlace('City Bowl', 'Cape Town', province: 'Western Cape'),
    SaPlace('Sea Point', 'Cape Town', province: 'Western Cape'),
    SaPlace('Green Point', 'Cape Town', province: 'Western Cape'),
    SaPlace('Mouille Point', 'Cape Town', province: 'Western Cape'),
    SaPlace('De Waterkant', 'Cape Town', province: 'Western Cape'),
    SaPlace('Bantry Bay', 'Cape Town', province: 'Western Cape'),
    SaPlace('Fresnaye', 'Cape Town', province: 'Western Cape'),
    SaPlace('Clifton', 'Cape Town', province: 'Western Cape'),
    SaPlace('Camps Bay', 'Cape Town', province: 'Western Cape'),
    SaPlace('Bakoven', 'Cape Town', province: 'Western Cape'),
    SaPlace('Llandudno', 'Cape Town', province: 'Western Cape'),
    SaPlace('Sandy Bay', 'Cape Town', province: 'Western Cape'),
    SaPlace('Hout Bay', 'Cape Town', province: 'Western Cape'),
    SaPlace('Atlantic Seaboard', 'Cape Town', province: 'Western Cape'),
    SaPlace('Constantia', 'Cape Town', province: 'Western Cape'),
    SaPlace('Bishopscourt', 'Cape Town', province: 'Western Cape'),
    SaPlace('Fernwood', 'Cape Town', province: 'Western Cape'),
    SaPlace('Newlands', 'Cape Town', province: 'Western Cape'),
    SaPlace('Claremont', 'Cape Town', province: 'Western Cape'),
    SaPlace('Kenilworth', 'Cape Town', province: 'Western Cape'),
    SaPlace('Wynberg', 'Cape Town', province: 'Western Cape'),
    SaPlace('Plumstead', 'Cape Town', province: 'Western Cape'),
    SaPlace('Tokai', 'Cape Town', province: 'Western Cape'),
    SaPlace('Steenberg', 'Cape Town', province: 'Western Cape'),
    SaPlace('Lakeside', 'Cape Town', province: 'Western Cape'),
    SaPlace('Muizenberg', 'Cape Town', province: 'Western Cape'),
    SaPlace('Kalk Bay', 'Cape Town', province: 'Western Cape'),
    SaPlace('Fish Hoek', 'Cape Town', province: 'Western Cape'),
    SaPlace('Sun Valley', 'Cape Town', province: 'Western Cape'),
    SaPlace('Noordhoek', 'Cape Town', province: 'Western Cape'),
    SaPlace('Kommetjie', 'Cape Town', province: 'Western Cape'),
    SaPlace("Simon's Town", 'Cape Town', province: 'Western Cape'),
    SaPlace('Glencairn', 'Cape Town', province: 'Western Cape'),
    SaPlace('Scarborough', 'Cape Town', province: 'Western Cape'),
    SaPlace('Rondebosch', 'Cape Town', province: 'Western Cape'),
    SaPlace('Observatory', 'Cape Town', province: 'Western Cape'),
    SaPlace('Mowbray', 'Cape Town', province: 'Western Cape'),
    SaPlace('Woodstock', 'Cape Town', province: 'Western Cape'),
    SaPlace('Salt River', 'Cape Town', province: 'Western Cape'),
    SaPlace('Bo-Kaap', 'Cape Town', province: 'Western Cape'),
    SaPlace('Gardens', 'Cape Town', province: 'Western Cape'),
    SaPlace('Oranjezicht', 'Cape Town', province: 'Western Cape'),
    SaPlace('Tamboerskloof', 'Cape Town', province: 'Western Cape'),
    SaPlace('Vredehoek', 'Cape Town', province: 'Western Cape'),
    SaPlace('Bloubergstrand', 'Cape Town', province: 'Western Cape'),
    SaPlace('Big Bay', 'Cape Town', province: 'Western Cape'),
    SaPlace('Sunset Beach', 'Cape Town', province: 'Western Cape'),
    SaPlace('Table View', 'Cape Town', province: 'Western Cape'),
    SaPlace('Parklands', 'Cape Town', province: 'Western Cape'),
    SaPlace('Milnerton', 'Cape Town', province: 'Western Cape'),
    SaPlace('Melkbosstrand', 'Cape Town', province: 'Western Cape'),
    SaPlace('Bellville', 'Western Cape', province: 'Western Cape'),
    SaPlace('Durbanville', 'Western Cape', province: 'Western Cape'),
    SaPlace('Kenridge', 'Durbanville', province: 'Western Cape'),
    SaPlace('Sonstraal Heights', 'Durbanville', province: 'Western Cape'),
    SaPlace('Welgemoed', 'Bellville', province: 'Western Cape'),
    SaPlace('Kraaifontein', 'Western Cape', province: 'Western Cape'),
    SaPlace('Brackenfell', 'Western Cape', province: 'Western Cape'),
    SaPlace('Kuilsrivier', 'Western Cape', province: 'Western Cape'),
    SaPlace('Stellenbosch', 'Western Cape', province: 'Western Cape'),
    SaPlace('Franschhoek', 'Western Cape', province: 'Western Cape'),
    SaPlace('Paarl', 'Western Cape', province: 'Western Cape'),
    SaPlace('Wellington', 'Western Cape', province: 'Western Cape'),
    SaPlace('Somerset West', 'Western Cape', province: 'Western Cape'),
    SaPlace('Strand', 'Somerset West', province: 'Western Cape'),
    SaPlace("Gordon's Bay", 'Somerset West', province: 'Western Cape'),
    SaPlace('Hermanus', 'Western Cape', province: 'Western Cape'),
    SaPlace('Onrus', 'Hermanus', province: 'Western Cape'),
    SaPlace('Pringle Bay', 'Western Cape', province: 'Western Cape'),
    SaPlace('Knysna', 'Garden Route', province: 'Western Cape'),
    SaPlace('Plettenberg Bay', 'Garden Route', province: 'Western Cape'),
    SaPlace('Wilderness', 'Garden Route', province: 'Western Cape'),
    SaPlace('Sedgefield', 'Garden Route', province: 'Western Cape'),
    SaPlace('George', 'Garden Route', province: 'Western Cape'),
    SaPlace('Mossel Bay', 'Garden Route', province: 'Western Cape'),
    SaPlace('Great Brak River', 'Garden Route', province: 'Western Cape'),
    SaPlace('Swellendam', 'Western Cape', province: 'Western Cape'),
    SaPlace('Worcester', 'Western Cape', province: 'Western Cape'),
    SaPlace('Robertson', 'Western Cape', province: 'Western Cape'),
    SaPlace('Montagu', 'Western Cape', province: 'Western Cape'),

    // ── KWAZULU-NATAL ────────────────────────────────────────────────────────
    SaPlace('Durban', 'KwaZulu-Natal', province: 'KwaZulu-Natal'),
    SaPlace('Umhlanga', 'KwaZulu-Natal', province: 'KwaZulu-Natal'),
    SaPlace('Umhlanga Ridge', 'Umhlanga', province: 'KwaZulu-Natal'),
    SaPlace('La Lucia', 'Durban', province: 'KwaZulu-Natal'),
    SaPlace('La Mercy', 'Durban', province: 'KwaZulu-Natal'),
    SaPlace('Umdloti', 'Durban', province: 'KwaZulu-Natal'),
    SaPlace('Durban North', 'Durban', province: 'KwaZulu-Natal'),
    SaPlace('Durban Central', 'Durban', province: 'KwaZulu-Natal'),
    SaPlace('Berea', 'Durban', province: 'KwaZulu-Natal'),
    SaPlace('Morningside', 'Durban', province: 'KwaZulu-Natal'),
    SaPlace('Essenwood', 'Durban', province: 'KwaZulu-Natal'),
    SaPlace('Musgrave', 'Durban', province: 'KwaZulu-Natal'),
    SaPlace('Glenwood', 'Durban', province: 'KwaZulu-Natal'),
    SaPlace('Glenashley', 'Durban', province: 'KwaZulu-Natal'),
    SaPlace('Bluff', 'Durban', province: 'KwaZulu-Natal'),
    SaPlace('Westville', 'Durban', province: 'KwaZulu-Natal'),
    SaPlace('Kloof', 'Durban', province: 'KwaZulu-Natal'),
    SaPlace('Hillcrest', 'Durban', province: 'KwaZulu-Natal'),
    SaPlace('Assagay', 'Durban', province: 'KwaZulu-Natal'),
    SaPlace('Pinetown', 'Durban', province: 'KwaZulu-Natal'),
    SaPlace('New Germany', 'Durban', province: 'KwaZulu-Natal'),
    SaPlace('Queensburgh', 'Durban', province: 'KwaZulu-Natal'),
    SaPlace('Chatsworth', 'Durban', province: 'KwaZulu-Natal'),
    SaPlace('Isipingo', 'Durban', province: 'KwaZulu-Natal'),
    SaPlace('Amanzimtoti', 'Durban', province: 'KwaZulu-Natal'),
    SaPlace('Warner Beach', 'South Coast', province: 'KwaZulu-Natal'),
    SaPlace('Ballito', 'KwaZulu-Natal', province: 'KwaZulu-Natal'),
    SaPlace('Salt Rock', 'Ballito', province: 'KwaZulu-Natal'),
    SaPlace('Shakas Rock', 'Ballito', province: 'KwaZulu-Natal'),
    SaPlace('Sheffield Beach', 'Ballito', province: 'KwaZulu-Natal'),
    SaPlace('Tinley Manor', 'Ballito', province: 'KwaZulu-Natal'),
    SaPlace('Zimbali', 'Ballito', province: 'KwaZulu-Natal'),
    SaPlace('Margate', 'South Coast', province: 'KwaZulu-Natal'),
    SaPlace('Ramsgate', 'South Coast', province: 'KwaZulu-Natal'),
    SaPlace('Shelly Beach', 'South Coast', province: 'KwaZulu-Natal'),
    SaPlace('Southbroom', 'South Coast', province: 'KwaZulu-Natal'),
    SaPlace('Port Shepstone', 'South Coast', province: 'KwaZulu-Natal'),
    SaPlace('Scottburgh', 'South Coast', province: 'KwaZulu-Natal'),
    SaPlace('Hibberdene', 'South Coast', province: 'KwaZulu-Natal'),
    SaPlace('Pennington', 'South Coast', province: 'KwaZulu-Natal'),
    SaPlace('Pietermaritzburg', 'KwaZulu-Natal', province: 'KwaZulu-Natal'),
    SaPlace('Howick', 'Pietermaritzburg', province: 'KwaZulu-Natal'),
    SaPlace('Nottingham Road', 'KZN Midlands', province: 'KwaZulu-Natal'),
    SaPlace('Mooi River', 'KwaZulu-Natal', province: 'KwaZulu-Natal'),
    SaPlace('Newcastle', 'KwaZulu-Natal', province: 'KwaZulu-Natal'),
    SaPlace('Dundee', 'KwaZulu-Natal', province: 'KwaZulu-Natal'),
    SaPlace('Greytown', 'KwaZulu-Natal', province: 'KwaZulu-Natal'),

    // ── EASTERN CAPE ─────────────────────────────────────────────────────────
    SaPlace('Gqeberha', 'Eastern Cape', province: 'Eastern Cape'),
    SaPlace('Summerstrand', 'Gqeberha', province: 'Eastern Cape'),
    SaPlace('Walmer', 'Gqeberha', province: 'Eastern Cape'),
    SaPlace('Humewood', 'Gqeberha', province: 'Eastern Cape'),
    SaPlace('Charlo', 'Gqeberha', province: 'Eastern Cape'),
    SaPlace('Parsons Hill', 'Gqeberha', province: 'Eastern Cape'),
    SaPlace('Lorraine', 'Gqeberha', province: 'Eastern Cape'),
    SaPlace('Uitenhage', 'Eastern Cape', province: 'Eastern Cape'),
    SaPlace('Jeffreys Bay', 'Eastern Cape', province: 'Eastern Cape'),
    SaPlace('Cape St Francis', 'Eastern Cape', province: 'Eastern Cape'),
    SaPlace('Humansdorp', 'Eastern Cape', province: 'Eastern Cape'),
    SaPlace('East London', 'Eastern Cape', province: 'Eastern Cape'),
    SaPlace('Beacon Bay', 'East London', province: 'Eastern Cape'),
    SaPlace('Nahoon', 'East London', province: 'Eastern Cape'),
    SaPlace('Gonubie', 'East London', province: 'Eastern Cape'),
    SaPlace('Makhanda', 'Eastern Cape', province: 'Eastern Cape'),
    SaPlace("King William's Town", 'Eastern Cape', province: 'Eastern Cape'),
    SaPlace('Queenstown', 'Eastern Cape', province: 'Eastern Cape'),
    SaPlace('Cradock', 'Eastern Cape', province: 'Eastern Cape'),

    // ── FREE STATE ────────────────────────────────────────────────────────────
    SaPlace('Bloemfontein', 'Free State', province: 'Free State'),
    SaPlace('Westdene', 'Bloemfontein', province: 'Free State'),
    SaPlace('Willows', 'Bloemfontein', province: 'Free State'),
    SaPlace('Universitas', 'Bloemfontein', province: 'Free State'),
    SaPlace('Langenhoven Park', 'Bloemfontein', province: 'Free State'),
    SaPlace('Dan Pienaar', 'Bloemfontein', province: 'Free State'),
    SaPlace('Heuwelsig', 'Bloemfontein', province: 'Free State'),
    SaPlace('Bainsvlei', 'Bloemfontein', province: 'Free State'),
    SaPlace('Welkom', 'Free State', province: 'Free State'),
    SaPlace('Sasolburg', 'Free State', province: 'Free State'),
    SaPlace('Bethlehem', 'Free State', province: 'Free State'),
    SaPlace('Harrismith', 'Free State', province: 'Free State'),
    SaPlace('Parys', 'Free State', province: 'Free State'),
    SaPlace('Kroonstad', 'Free State', province: 'Free State'),

    // ── LIMPOPO ───────────────────────────────────────────────────────────────
    SaPlace('Polokwane', 'Limpopo', province: 'Limpopo'),
    SaPlace('Bendor', 'Polokwane', province: 'Limpopo'),
    SaPlace('Mokopane', 'Limpopo', province: 'Limpopo'),
    SaPlace('Tzaneen', 'Limpopo', province: 'Limpopo'),
    SaPlace('Phalaborwa', 'Limpopo', province: 'Limpopo'),
    SaPlace('Bela-Bela', 'Limpopo', province: 'Limpopo'),
    SaPlace('Louis Trichardt', 'Limpopo', province: 'Limpopo'),
    SaPlace('Musina', 'Limpopo', province: 'Limpopo'),
    SaPlace('Lephalale', 'Limpopo', province: 'Limpopo'),
    SaPlace('Thabazimbi', 'Limpopo', province: 'Limpopo'),

    // ── MPUMALANGA ────────────────────────────────────────────────────────────
    SaPlace('Mbombela', 'Mpumalanga', province: 'Mpumalanga'),
    SaPlace('White River', 'Mpumalanga', province: 'Mpumalanga'),
    SaPlace('Hazyview', 'Mpumalanga', province: 'Mpumalanga'),
    SaPlace('Sabie', 'Mpumalanga', province: 'Mpumalanga'),
    SaPlace('Graskop', 'Mpumalanga', province: 'Mpumalanga'),
    SaPlace('Barberton', 'Mpumalanga', province: 'Mpumalanga'),
    SaPlace('eMalahleni', 'Mpumalanga', province: 'Mpumalanga'),
    SaPlace('Middelburg', 'Mpumalanga', province: 'Mpumalanga'),
    SaPlace('Secunda', 'Mpumalanga', province: 'Mpumalanga'),
    SaPlace('Standerton', 'Mpumalanga', province: 'Mpumalanga'),
    SaPlace('Ermelo', 'Mpumalanga', province: 'Mpumalanga'),

    // ── NORTH WEST ────────────────────────────────────────────────────────────
    SaPlace('Rustenburg', 'North West', province: 'North West'),
    SaPlace('Potchefstroom', 'North West', province: 'North West'),
    SaPlace('Klerksdorp', 'North West', province: 'North West'),
    SaPlace('Mahikeng', 'North West', province: 'North West'),
    SaPlace('Brits', 'North West', province: 'North West'),
    SaPlace('Fochville', 'North West', province: 'North West'),
    SaPlace('Carletonville', 'North West', province: 'North West'),
    SaPlace('Lichtenburg', 'North West', province: 'North West'),
    SaPlace('Vryburg', 'North West', province: 'North West'),

    // ── NORTHERN CAPE ─────────────────────────────────────────────────────────
    SaPlace('Kimberley', 'Northern Cape', province: 'Northern Cape'),
    SaPlace('Galeshewe', 'Kimberley', province: 'Northern Cape'),
    SaPlace('Upington', 'Northern Cape', province: 'Northern Cape'),
    SaPlace('Springbok', 'Northern Cape', province: 'Northern Cape'),
    SaPlace('Kuruman', 'Northern Cape', province: 'Northern Cape'),
    SaPlace('Kathu', 'Northern Cape', province: 'Northern Cape'),
    SaPlace('De Aar', 'Northern Cape', province: 'Northern Cape'),
    SaPlace('Colesberg', 'Northern Cape', province: 'Northern Cape'),
  ];
}
